config/routes.rb
Wisply::Application.routes.draw do

  resources :assignments

  devise_for :users

  resources :common_cores

  resources :assignments
  root :to => 'assignments#index'

  match '/auth/:provider/callback', :to => 'sessions#create'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :author, :common_core, :description, :educational_use, :in_language, :intended_end_userole, :interactivity_type, :is_based_on_url, :learning_resource_type, :location, :publisher_id, :time_required, :title, :typical_age_range, :use_rights_url
end


#author common_core description educational_use in_language intended_end_userole interactivity_type is_based_on_url learning_resource_type location publisher_id time_required title typical_age_rangeuse_rights_url

app/models/common_core.rb
class CommonCore < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/common_cores_controller.rb
class CommonCoresController < ApplicationController
  # GET /common_cores
  # GET /common_cores.json
  def index
    @common_cores = CommonCore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @common_cores }
    end
  end

  # GET /common_cores/1
  # GET /common_cores/1.json
  def show
    @common_core = CommonCore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @common_core }
    end
  end

  # GET /common_cores/new
  # GET /common_cores/new.json
  def new
    @common_core = CommonCore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @common_core }
    end
  end

  # GET /common_cores/1/edit
  def edit
    @common_core = CommonCore.find(params[:id])
  end

  # POST /common_cores
  # POST /common_cores.json
  def create
    @common_core = CommonCore.new(params[:common_core])

    respond_to do |format|
      if @common_core.save
        format.html { redirect_to @common_core, :notice => 'Common core was successfully created.' }
        format.json { render :json => @common_core, :status => :created, :location => @common_core }
      else
        format.html { render :action => "new" }
        format.json { render :json => @common_core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /common_cores/1
  # PUT /common_cores/1.json
  def update
    @common_core = CommonCore.find(params[:id])

    respond_to do |format|
      if @common_core.update_attributes(params[:common_core])
        format.html { redirect_to @common_core, :notice => 'Common core was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @common_core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /common_cores/1
  # DELETE /common_cores/1.json
  def destroy
    @common_core = CommonCore.find(params[:id])
    @common_core.destroy

    respond_to do |format|
      format.html { redirect_to common_cores_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    p auth_hash.inspect
    Rails.logger.info auth_hash.inspect
    # @user = User.find_or_create_from_auth_hash(auth_hash)
    # self.current_user = @user
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/common_cores_helper.rb
module CommonCoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :common_core %><br />
    <%= f.text_field :common_core %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :educational_use %><br />
    <%= f.text_field :educational_use %>
  </div>
  <div class="field">
    <%= f.label :in_language %><br />
    <%= f.text_field :in_language %>
  </div>
  <div class="field">
    <%= f.label :intended_end_userole %><br />
    <%= f.text_field :intended_end_userole %>
  </div>
  <div class="field">
    <%= f.label :interactivity_type %><br />
    <%= f.text_field :interactivity_type %>
  </div>
  <div class="field">
    <%= f.label :is_based_on_url %><br />
    <%= f.text_field :is_based_on_url %>
  </div>
  <div class="field">
    <%= f.label :learning_resource_type %><br />
    <%= f.text_field :learning_resource_type %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :publisher_id %><br />
    <%= f.text_field :publisher_id %>
  </div>
  <div class="field">
    <%= f.label :time_required %><br />
    <%= f.text_field :time_required %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :typical_age_range %><br />
    <%= f.text_field :typical_age_range %>
  </div>
  <div class="field">
    <%= f.label :use_rights_url %><br />
    <%= f.text_field :use_rights_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Common core</th>
    <th>Description</th>
    <th>Educational use</th>
    <th>In language</th>
    <th>Intended end userole</th>
    <th>Interactivity type</th>
    <th>Is based on url</th>
    <th>Learning resource type</th>
    <th>Location</th>
    <th>Publisher</th>
    <th>Time required</th>
    <th>Title</th>
    <th>Typical age range</th>
    <th>Use rights url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.author %></td>
    <td><%= assignment.common_core %></td>
    <td><%= assignment.description %></td>
    <td><%= assignment.educational_use %></td>
    <td><%= assignment.in_language %></td>
    <td><%= assignment.intended_end_userole %></td>
    <td><%= assignment.interactivity_type %></td>
    <td><%= assignment.is_based_on_url %></td>
    <td><%= assignment.learning_resource_type %></td>
    <td><%= assignment.location %></td>
    <td><%= assignment.publisher_id %></td>
    <td><%= assignment.time_required %></td>
    <td><%= assignment.title %></td>
    <td><%= assignment.typical_age_range %></td>
    <td><%= assignment.use_rights_url %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @assignment.author %>
</p>

<p>
  <b>Common core:</b>
  <%= @assignment.common_core %>
</p>

<p>
  <b>Description:</b>
  <%= @assignment.description %>
</p>

<p>
  <b>Educational use:</b>
  <%= @assignment.educational_use %>
</p>

<p>
  <b>In language:</b>
  <%= @assignment.in_language %>
</p>

<p>
  <b>Intended end userole:</b>
  <%= @assignment.intended_end_userole %>
</p>

<p>
  <b>Interactivity type:</b>
  <%= @assignment.interactivity_type %>
</p>

<p>
  <b>Is based on url:</b>
  <%= @assignment.is_based_on_url %>
</p>

<p>
  <b>Learning resource type:</b>
  <%= @assignment.learning_resource_type %>
</p>

<p>
  <b>Location:</b>
  <%= @assignment.location %>
</p>

<p>
  <b>Publisher:</b>
  <%= @assignment.publisher_id %>
</p>

<p>
  <b>Time required:</b>
  <%= @assignment.time_required %>
</p>

<p>
  <b>Title:</b>
  <%= @assignment.title %>
</p>

<p>
  <b>Typical age range:</b>
  <%= @assignment.typical_age_range %>
</p>

<p>
  <b>Use rights url:</b>
  <%= @assignment.use_rights_url %>
</p>


<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>

app/views/common_cores/_form.html.erb
<%= form_for(@common_core) do |f| %>
  <% if @common_core.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@common_core.errors.count, "error") %> prohibited this common_core from being saved:</h2>

      <ul>
      <% @common_core.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/common_cores/edit.html.erb
<h1>Editing common_core</h1>

<%= render 'form' %>

<%= link_to 'Show', @common_core %> |
<%= link_to 'Back', common_cores_path %>

app/views/common_cores/index.html.erb
<h1>Listing common_cores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @common_cores.each do |common_core| %>
  <tr>
    <td><%= common_core.name %></td>
    <td><%= common_core.description %></td>
    <td><%= link_to 'Show', common_core %></td>
    <td><%= link_to 'Edit', edit_common_core_path(common_core) %></td>
    <td><%= link_to 'Destroy', common_core, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Common core', new_common_core_path %>

app/views/common_cores/new.html.erb
<h1>New common_core</h1>

<%= render 'form' %>

<%= link_to 'Back', common_cores_path %>

app/views/common_cores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @common_core.name %>
</p>

<p>
  <b>Description:</b>
  <%= @common_core.description %>
</p>


<%= link_to 'Edit', edit_common_core_path(@common_core) %> |
<%= link_to 'Back', common_cores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wisply" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Wisply</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "login with facebook", "/auth/facebook"  %></li>
              <li><%= link_to "login with email", "/login"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <!-- <div class="well sidebar-nav">
                   <h3>Sidebar</h3>
                   <ul class="nav nav-list">
                     <li class="nav-header">Sidebar</li>
                     <li><%= link_to "login with facebook", "/auth/facebook"  %></li>
                     <li><%= link_to "login", "/users/sign_in"  %></li>
                     <li><%= link_to "Link3", "/path3"  %></li>
                   </ul>
                 </div> --><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>